module.exports = (row) => ({
  collisionId: row[22],
  collisionYear: row[0],
  collisionMonth: row[1],
  collisionDay: row[2],
  collisionHour: row[3],
  collisionSeverity: row[4],
  numberOfVehicles: row[5],
  collisionConfiguration: row[6],
  roadwayConfiguration: row[7],
  weatherCondition: row[8],
  roadSurface: row[9],
  roadAlignment: row[10],
  trafficControl: row[11],
  vehicleSequenceNumber: row[12],
  vehicleType: row[13],
  vehicleModelYear: row[14],
  personSequenceNumber: row[15],
  personSex: row[16],
  personAge: row[17],
  personPosition: row[18],
  medicalTreatmentRequired: row[19],
  safetyDeviceUsed: row[20],
  roadUserClass: row[21]
})
